/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import gasolinera.ColaN;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author JairoDev
 */
public class GasolineraVista extends javax.swing.JFrame {

    /**
     * Creates new form GasolineraVista
     */
    ColaN fifo = new ColaN();
    private int sizeP = 5;
    private int con = 0;
    ArrayList<JLabel> autosL = new ArrayList<>();

    public GasolineraVista() {
        initComponents();
        ocultarCarros();
        insertarCarros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bomba2 = new javax.swing.JLabel();
        bomba3 = new javax.swing.JLabel();
        bomba1 = new javax.swing.JLabel();
        carF3 = new javax.swing.JLabel();
        carF6 = new javax.swing.JLabel();
        carF5 = new javax.swing.JLabel();
        carF1 = new javax.swing.JLabel();
        carF4 = new javax.swing.JLabel();
        bomba4 = new javax.swing.JLabel();
        carB4 = new javax.swing.JLabel();
        carF2 = new javax.swing.JLabel();
        carB1 = new javax.swing.JLabel();
        carB2 = new javax.swing.JLabel();
        carB3 = new javax.swing.JLabel();
        panelB4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel32 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        carW3 = new javax.swing.JLabel();
        carW1 = new javax.swing.JLabel();
        carW4 = new javax.swing.JLabel();
        carW2 = new javax.swing.JLabel();
        panelB1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jProgressBar2 = new javax.swing.JProgressBar();
        panelB2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jProgressBar3 = new javax.swing.JProgressBar();
        jLabel34 = new javax.swing.JLabel();
        panelB3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jProgressBar4 = new javax.swing.JProgressBar();
        jLabel35 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gasolinera");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bomba2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dispensario2.png"))); // NOI18N
        bomba2.setText(" ");
        getContentPane().add(bomba2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, -1));

        bomba3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dispensario2.png"))); // NOI18N
        getContentPane().add(bomba3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, -1, -1));

        bomba1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dispensario2.png"))); // NOI18N
        getContentPane().add(bomba1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        carF3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carro.png"))); // NOI18N
        getContentPane().add(carF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 210, 90));

        carF6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carro.png"))); // NOI18N
        getContentPane().add(carF6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 400, 210, 90));

        carF5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carro.png"))); // NOI18N
        getContentPane().add(carF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 400, 210, 90));

        carF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carro.png"))); // NOI18N
        getContentPane().add(carF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 210, 90));

        carF4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carro.png"))); // NOI18N
        getContentPane().add(carF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 210, 90));

        bomba4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dispensario2.png"))); // NOI18N
        getContentPane().add(bomba4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, -1, -1));

        carB4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carro.png"))); // NOI18N
        getContentPane().add(carB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 270, 210, 90));

        carF2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carro.png"))); // NOI18N
        getContentPane().add(carF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 210, 90));

        carB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carro.png"))); // NOI18N
        getContentPane().add(carB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 210, 90));

        carB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carro.png"))); // NOI18N
        getContentPane().add(carB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 210, 90));

        carB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carro.png"))); // NOI18N
        getContentPane().add(carB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 210, 90));

        panelB4.setBorder(javax.swing.BorderFactory.createTitledBorder("Bomba4"));
        panelB4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Q.");
        panelB4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 20, 20));

        jTextField1.setBorder(null);
        panelB4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, 30));

        jButton1.setText("Iniciar");
        panelB4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));
        panelB4.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 162, 150, 20));

        jLabel32.setText("00.00");
        panelB4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        getContentPane().add(panelB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 40, 200, 220));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carwash.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 320, 300));

        carW3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carro.png"))); // NOI18N
        getContentPane().add(carW3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 540, 210, 90));

        carW1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carro.png"))); // NOI18N
        getContentPane().add(carW1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, 210, 90));

        carW4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carro.png"))); // NOI18N
        getContentPane().add(carW4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 540, 210, 90));

        carW2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carro.png"))); // NOI18N
        getContentPane().add(carW2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 540, 210, 90));

        panelB1.setBorder(javax.swing.BorderFactory.createTitledBorder("Bomba1"));
        panelB1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Q.");
        panelB1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 20, 20));

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setBorder(null);
        panelB1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, 30));

        jButton2.setText("Iniciar");
        panelB1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));
        panelB1.add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 162, 150, 20));

        getContentPane().add(panelB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 200, 220));

        panelB2.setBorder(javax.swing.BorderFactory.createTitledBorder("Bomba2"));
        panelB2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setText("Q.");
        panelB2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 20, 20));

        jTextField3.setBorder(null);
        panelB2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, 30));

        jButton3.setText("Iniciar");
        panelB2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));
        panelB2.add(jProgressBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 162, 150, 20));

        jLabel34.setText("00.00");
        panelB2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        getContentPane().add(panelB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 200, 220));

        panelB3.setBorder(javax.swing.BorderFactory.createTitledBorder("Bomba3"));
        panelB3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("Q.");
        panelB3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 20, 20));

        jTextField4.setBorder(null);
        panelB3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, 30));

        jButton4.setText("Iniciar");
        panelB3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));
        panelB3.add(jProgressBar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 162, 150, 20));

        jLabel35.setText("00.00");
        panelB3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        getContentPane().add(panelB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 40, 200, 220));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carrtera.jpg"))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 280, 660, 110));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carrtera.jpg"))); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 110));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carrtera.jpg"))); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 550, -1, 110));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carrtera.jpg"))); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, 660, 110));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carrtera.jpg"))); // NOI18N
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 110));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carrtera.jpg"))); // NOI18N
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, -1, 110));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gramaH.jpg"))); // NOI18N
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 270, -1, 240));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gramaH.jpg"))); // NOI18N
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, 240));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gramaH.jpg"))); // NOI18N
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, 240));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gramaH.jpg"))); // NOI18N
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, -1, 430));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gramaH.jpg"))); // NOI18N
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 370, -1, 430));

        jButton5.setText("Nuevo Carro");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 680, -1, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gramaH.jpg"))); // NOI18N
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, 430));

        jLabel33.setText("00.00");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (fifo.sizeC() > sizeP) {
            System.out.println("Ya no se permiten carros");
        } else {
            fifo.push(con);
            autosL.get(con).setVisible(true);
            con++;
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GasolineraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GasolineraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GasolineraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GasolineraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GasolineraVista().setVisible(true);
            }
        });
    }

    private void ocultarCarros() {
        carB1.setVisible(false);
        carB2.setVisible(false);
        carB3.setVisible(false);
        carB4.setVisible(false);
        carF1.setVisible(false);
        carF2.setVisible(false);
        carF3.setVisible(false);
        carF4.setVisible(false);
        carF5.setVisible(false);
        carF6.setVisible(false);
        carW1.setVisible(false);
        carW2.setVisible(false);
        carW3.setVisible(false);
        carW4.setVisible(false);
    }

    private void insertarCarros() {

        autosL.add(carF1);
        autosL.add(carF2);
        autosL.add(carF3);
        autosL.add(carF4);
        autosL.add(carF5);
        autosL.add(carF6);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bomba1;
    private javax.swing.JLabel bomba2;
    private javax.swing.JLabel bomba3;
    private javax.swing.JLabel bomba4;
    private javax.swing.JLabel carB1;
    private javax.swing.JLabel carB2;
    private javax.swing.JLabel carB3;
    private javax.swing.JLabel carB4;
    private javax.swing.JLabel carF1;
    private javax.swing.JLabel carF2;
    private javax.swing.JLabel carF3;
    private javax.swing.JLabel carF4;
    private javax.swing.JLabel carF5;
    private javax.swing.JLabel carF6;
    private javax.swing.JLabel carW1;
    private javax.swing.JLabel carW2;
    private javax.swing.JLabel carW3;
    private javax.swing.JLabel carW4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel panelB1;
    private javax.swing.JPanel panelB2;
    private javax.swing.JPanel panelB3;
    private javax.swing.JPanel panelB4;
    // End of variables declaration//GEN-END:variables
}
